export const SKILL_CATEGORIES = [
  "Langage de programmation",
  "Framework & Bibliothèque",
  "Base de données",
  "Data & Machine Learning",
  "Data Engineering & Big Data",
  "Cloud & DevOps",
  "Cybersécurité",
  "Outils de développement",
  "Outils collaboratifs & Productivité",
  "Design & Créativité",
  "Gestion de projet & Produit",
  "Marketing & Communication",
  "Business & Finance",
  "Soft Skills",
  "Langues",
  "Outils bureautiques",
  "Autre",
  "Ingénierie & CAO",
  "Architecture & Construction",
  "Transport & Logistique",
  "Certifications & Permis",
  "Santé & Social",
  "Hôtellerie & Restauration",
  "Sciences & Recherche",
] as const;

export type SkillCategory = (typeof SKILL_CATEGORIES)[number];

// Référentiel de compétences avec catégories auto-assignées
// Inspiré de LinkedIn / Indeed / StackOverflow tags
export const SKILLS_DATABASE: Record<string, SkillCategory> = {
  // === Langages de programmation ===
  JavaScript: "Langage de programmation",
  TypeScript: "Langage de programmation",
  Python: "Langage de programmation",
  Java: "Langage de programmation",
  "C++": "Langage de programmation",
  "C#": "Langage de programmation",
  C: "Langage de programmation",
  PHP: "Langage de programmation",
  Ruby: "Langage de programmation",
  Go: "Langage de programmation",
  Rust: "Langage de programmation",
  Swift: "Langage de programmation",
  Kotlin: "Langage de programmation",
  Dart: "Langage de programmation",
  Scala: "Langage de programmation",
  R: "Langage de programmation",
  MATLAB: "Langage de programmation",
  Julia: "Langage de programmation",
  Haskell: "Langage de programmation",
  Elixir: "Langage de programmation",
  Perl: "Langage de programmation",
  Shell: "Langage de programmation",
  Bash: "Langage de programmation",
  PowerShell: "Langage de programmation",
  SQL: "Langage de programmation",
  HTML: "Langage de programmation",
  CSS: "Langage de programmation",

  // === Frameworks & Bibliothèques (Front / Mobile) ===
  React: "Framework & Bibliothèque",
  "React Native": "Framework & Bibliothèque",
  "Next.js": "Framework & Bibliothèque",
  Remix: "Framework & Bibliothèque",
  Astro: "Framework & Bibliothèque",
  "Vue.js": "Framework & Bibliothèque",
  "Nuxt.js": "Framework & Bibliothèque",
  Angular: "Framework & Bibliothèque",
  Svelte: "Framework & Bibliothèque",
  SvelteKit: "Framework & Bibliothèque",
  Flutter: "Framework & Bibliothèque",
  Ionic: "Framework & Bibliothèque",
  Expo: "Framework & Bibliothèque",
  Electron: "Framework & Bibliothèque",

  // === Frameworks & Bibliothèques (Back / Fullstack) ===
  "Node.js": "Framework & Bibliothèque",
  Express: "Framework & Bibliothèque",
  NestJS: "Framework & Bibliothèque",
  Fastify: "Framework & Bibliothèque",
  FastAPI: "Framework & Bibliothèque",
  Django: "Framework & Bibliothèque",
  "Django REST Framework": "Framework & Bibliothèque",
  Flask: "Framework & Bibliothèque",
  "Spring Boot": "Framework & Bibliothèque",
  Spring: "Framework & Bibliothèque",
  Laravel: "Framework & Bibliothèque",
  Symfony: "Framework & Bibliothèque",
  "Ruby on Rails": "Framework & Bibliothèque",
  "ASP.NET": "Framework & Bibliothèque",
  ".NET Core": "Framework & Bibliothèque",
  Phoenix: "Framework & Bibliothèque",

  // === UI / CSS / State management ===
  TailwindCSS: "Framework & Bibliothèque",
  Bootstrap: "Framework & Bibliothèque",
  "Chakra UI": "Framework & Bibliothèque",
  "Material UI": "Framework & Bibliothèque",
  "Ant Design": "Framework & Bibliothèque",
  Redux: "Framework & Bibliothèque",
  Zustand: "Framework & Bibliothèque",
  MobX: "Framework & Bibliothèque",
  "React Query": "Framework & Bibliothèque",
  "TanStack Query": "Framework & Bibliothèque",
  jQuery: "Framework & Bibliothèque",

  // === Bases de données & Stockage ===
  PostgreSQL: "Base de données",
  MySQL: "Base de données",
  MariaDB: "Base de données",
  SQLite: "Base de données",
  Oracle: "Base de données",
  "Microsoft SQL Server": "Base de données",
  MongoDB: "Base de données",
  Redis: "Base de données",
  Elasticsearch: "Base de données",
  OpenSearch: "Base de données",
  Cassandra: "Base de données",
  DynamoDB: "Base de données",
  CouchDB: "Base de données",
  Neo4j: "Base de données",
  InfluxDB: "Base de données",
  ClickHouse: "Base de données",
  BigQuery: "Base de données",
  Snowflake: "Base de données",
  "Amazon Redshift": "Base de données",
  "Firebase Realtime Database": "Base de données",
  Firestore: "Base de données",
  Supabase: "Base de données",
  PlanetScale: "Base de données",

  // === Data & Machine Learning ===
  Pandas: "Data & Machine Learning",
  NumPy: "Data & Machine Learning",
  Matplotlib: "Data & Machine Learning",
  Seaborn: "Data & Machine Learning",
  "Scikit-learn": "Data & Machine Learning",
  TensorFlow: "Data & Machine Learning",
  Keras: "Data & Machine Learning",
  PyTorch: "Data & Machine Learning",
  XGBoost: "Data & Machine Learning",
  LightGBM: "Data & Machine Learning",
  CatBoost: "Data & Machine Learning",
  Statsmodels: "Data & Machine Learning",
  "Jupyter Notebook": "Data & Machine Learning",
  JupyterLab: "Data & Machine Learning",
  MLflow: "Data & Machine Learning",
  "Weights & Biases": "Data & Machine Learning",
  "Computer Vision": "Data & Machine Learning",
  NLP: "Data & Machine Learning",
  LLM: "Data & Machine Learning",
  "Prompt Engineering": "Data & Machine Learning",
  MLOps: "Data & Machine Learning",
  "Data Visualization": "Data & Machine Learning",
  "Feature Engineering": "Data & Machine Learning",

  // === Data Engineering & Big Data ===
  "Apache Spark": "Data Engineering & Big Data",
  PySpark: "Data Engineering & Big Data",
  Hadoop: "Data Engineering & Big Data",
  Hive: "Data Engineering & Big Data",
  "Apache Flink": "Data Engineering & Big Data",
  "Apache Beam": "Data Engineering & Big Data",
  "Apache Kafka": "Data Engineering & Big Data",
  "Apache Airflow": "Data Engineering & Big Data",
  dbt: "Data Engineering & Big Data",
  NiFi: "Data Engineering & Big Data",
  Talend: "Data Engineering & Big Data",
  Informatica: "Data Engineering & Big Data",
  "Data Lake": "Data Engineering & Big Data",
  ETL: "Data Engineering & Big Data",
  ELT: "Data Engineering & Big Data",
  "Data Warehousing": "Data Engineering & Big Data",
  "Data Pipeline": "Data Engineering & Big Data",
  Databricks: "Data Engineering & Big Data",
  "Snowflake (Data Cloud)": "Data Engineering & Big Data",
  "Azure Synapse": "Data Engineering & Big Data",
  "BigQuery (GCP)": "Data Engineering & Big Data",

  // === Cloud & DevOps ===
  Docker: "Cloud & DevOps",
  Kubernetes: "Cloud & DevOps",
  Git: "Cloud & DevOps",
  GitHub: "Cloud & DevOps",
  GitLab: "Cloud & DevOps",
  Bitbucket: "Cloud & DevOps",
  "GitHub Actions": "Cloud & DevOps",
  "GitLab CI": "Cloud & DevOps",
  Jenkins: "Cloud & DevOps",
  CircleCI: "Cloud & DevOps",
  "Travis CI": "Cloud & DevOps",
  "CI/CD": "Cloud & DevOps",
  AWS: "Cloud & DevOps",
  "Amazon S3": "Cloud & DevOps",
  "AWS Lambda": "Cloud & DevOps",
  Azure: "Cloud & DevOps",
  "Google Cloud": "Cloud & DevOps",
  "Firebase Hosting": "Cloud & DevOps",
  Vercel: "Cloud & DevOps",
  Netlify: "Cloud & DevOps",
  Render: "Cloud & DevOps",
  DigitalOcean: "Cloud & DevOps",
  Railway: "Cloud & DevOps",
  Heroku: "Cloud & DevOps",
  Cloudflare: "Cloud & DevOps",
  Terraform: "Cloud & DevOps",
  Pulumi: "Cloud & DevOps",
  Ansible: "Cloud & DevOps",
  Chef: "Cloud & DevOps",
  Puppet: "Cloud & DevOps",
  Helm: "Cloud & DevOps",
  "Argo CD": "Cloud & DevOps",
  Prometheus: "Cloud & DevOps",
  Grafana: "Cloud & DevOps",
  "ELK Stack": "Cloud & DevOps",
  Linux: "Cloud & DevOps",
  Nginx: "Cloud & DevOps",
  Apache: "Cloud & DevOps",

  // === Cybersécurité ===
  Cybersecurity: "Cybersécurité",
  OWASP: "Cybersécurité",
  Pentesting: "Cybersécurité",
  "Burp Suite": "Cybersécurité",
  Metasploit: "Cybersécurité",
  Wireshark: "Cybersécurité",
  SIEM: "Cybersécurité",
  "IDS/IPS": "Cybersécurité",
  IAM: "Cybersécurité",
  "ISO 27001": "Cybersécurité",
  "SOC Analyst": "Cybersécurité",
  "Network Security": "Cybersécurité",
  AppSec: "Cybersécurité",
  Cryptography: "Cybersécurité",

  // === Outils de développement ===
  "VS Code": "Outils de développement",
  "IntelliJ IDEA": "Outils de développement",
  WebStorm: "Outils de développement",
  PhpStorm: "Outils de développement",
  PyCharm: "Outils de développement",
  "Android Studio": "Outils de développement",
  Xcode: "Outils de développement",
  Eclipse: "Outils de développement",
  "Visual Studio": "Outils de développement",
  Postman: "Outils de développement",
  Insomnia: "Outils de développement",
  "Swagger/OpenAPI": "Outils de développement",
  Fiddler: "Outils de développement",
  GitKraken: "Outils de développement",
  SourceTree: "Outils de développement",
  "Figma Dev Mode": "Outils de développement",

  // === Outils collaboratifs & Productivité ===
  Notion: "Outils collaboratifs & Productivité",
  Confluence: "Outils collaboratifs & Productivité",
  Slack: "Outils collaboratifs & Productivité",
  "Microsoft Teams": "Outils collaboratifs & Productivité",
  Discord: "Outils collaboratifs & Productivité",
  Zoom: "Outils collaboratifs & Productivité",
  Miro: "Outils collaboratifs & Productivité",
  FigJam: "Outils collaboratifs & Productivité",
  "Google Workspace": "Outils collaboratifs & Productivité",
  "Microsoft 365": "Outils collaboratifs & Productivité",

  // === Design & Créativité ===
  Figma: "Design & Créativité",
  "Adobe Photoshop": "Design & Créativité",
  "Adobe Illustrator": "Design & Créativité",
  "Adobe XD": "Design & Créativité",
  "Adobe Premiere Pro": "Design & Créativité",
  "Adobe After Effects": "Design & Créativité",
  InDesign: "Design & Créativité",
  Sketch: "Design & Créativité",
  InVision: "Design & Créativité",
  Canva: "Design & Créativité",
  "UI/UX Design": "Design & Créativité",
  "Design System": "Design & Créativité",
  Prototypage: "Design & Créativité",
  Wireframing: "Design & Créativité",
  "User Research": "Design & Créativité",
  "Design Thinking": "Design & Créativité",
  "Storytelling visuel": "Design & Créativité",
  Blender: "Design & Créativité",
  "3D Modeling": "Design & Créativité",

  // === Gestion de projet & Produit ===
  Scrum: "Gestion de projet & Produit",
  Agile: "Gestion de projet & Produit",
  Kanban: "Gestion de projet & Produit",
  Lean: "Gestion de projet & Produit",
  Jira: "Gestion de projet & Produit",
  Trello: "Gestion de projet & Produit",
  Asana: "Gestion de projet & Produit",
  "Monday.com": "Gestion de projet & Produit",
  ClickUp: "Gestion de projet & Produit",
  "Notion (gestion de projet)": "Gestion de projet & Produit",
  "Roadmapping produit": "Gestion de projet & Produit",
  "Product Management": "Gestion de projet & Produit",
  "Product Owner": "Gestion de projet & Produit",
  "Scrum Master": "Gestion de projet & Produit",
  "Gestion d'équipe": "Gestion de projet & Produit",
  "Planification stratégique": "Gestion de projet & Produit",
  OKR: "Gestion de projet & Produit",
  "Gestion des risques": "Gestion de projet & Produit",

  // === Marketing & Communication ===
  "Marketing Digital": "Marketing & Communication",
  SEO: "Marketing & Communication",
  SEM: "Marketing & Communication",
  SEA: "Marketing & Communication",
  "Google Analytics": "Marketing & Communication",
  "Google Ads": "Marketing & Communication",
  "Facebook Ads": "Marketing & Communication",
  "Social Media Marketing": "Marketing & Communication",
  "Content Marketing": "Marketing & Communication",
  Copywriting: "Marketing & Communication",
  "Email Marketing": "Marketing & Communication",
  "Marketing Automation": "Marketing & Communication",
  "Growth Hacking": "Marketing & Communication",
  "Community Management": "Marketing & Communication",
  "Stratégie de marque": "Marketing & Communication",
  "Relations publiques": "Marketing & Communication",
  "Influence Marketing": "Marketing & Communication",
  "UX Writing": "Marketing & Communication",
  Communication: "Marketing & Communication",

  // === Business & Finance ===
  Excel: "Business & Finance",
  "Google Sheets": "Business & Finance",
  "Power BI": "Business & Finance",
  Tableau: "Business & Finance",
  "Looker Studio": "Business & Finance",
  "Analyse de données": "Business & Finance",
  "Data Analysis": "Business & Finance",
  "Business Intelligence": "Business & Finance",
  Comptabilité: "Business & Finance",
  Finance: "Business & Finance",
  "Analyse financière": "Business & Finance",
  "Gestion budgétaire": "Business & Finance",
  "Contrôle de gestion": "Business & Finance",
  SAP: "Business & Finance",
  Salesforce: "Business & Finance",
  HubSpot: "Business & Finance",
  CRM: "Business & Finance",
  ERP: "Business & Finance",
  "Stratégie commerciale": "Business & Finance",
  "Négociation commerciale": "Business & Finance",

  // === Soft Skills ===
  Leadership: "Soft Skills",
  "Communication orale": "Soft Skills",
  "Communication écrite": "Soft Skills",
  "Travail d'équipe": "Soft Skills",
  "Résolution de problèmes": "Soft Skills",
  Créativité: "Soft Skills",
  "Pensée critique": "Soft Skills",
  Adaptabilité: "Soft Skills",
  "Gestion du temps": "Soft Skills",
  Organisation: "Soft Skills",
  "Esprit d'initiative": "Soft Skills",
  Autonomie: "Soft Skills",
  "Gestion du stress": "Soft Skills",
  Empathie: "Soft Skills",
  "Écoute active": "Soft Skills",
  "Prise de décision": "Soft Skills",
  Négociation: "Soft Skills",
  "Sens du service": "Soft Skills",
  "Esprit d'analyse": "Soft Skills",
  "Esprit de synthèse": "Soft Skills",
  "Confiance en soi": "Soft Skills",
  "Capacité d'apprentissage": "Soft Skills",
  "Présentations orales": "Soft Skills",
  "Prise de parole en public": "Soft Skills",

  // === Langues ===
  Français: "Langues",
  Anglais: "Langues",
  Espagnol: "Langues",
  Allemand: "Langues",
  Italien: "Langues",
  Portugais: "Langues",
  Arabe: "Langues",
  "Chinois (Mandarin)": "Langues",
  Japonais: "Langues",
  Coréen: "Langues",
  Russe: "Langues",
  Néerlandais: "Langues",
  Turc: "Langues",
  Polonais: "Langues",
  Hindi: "Langues",

  // === Outils bureautiques ===
  "Microsoft Word": "Outils bureautiques",
  "Microsoft Excel (avancé)": "Outils bureautiques",
  "Microsoft PowerPoint": "Outils bureautiques",
  "Microsoft Outlook": "Outils bureautiques",
  "Google Docs": "Outils bureautiques",
  "Google Sheets (avancé)": "Outils bureautiques",
  "Google Slides": "Outils bureautiques",
  LaTeX: "Outils bureautiques",

  // === Ingénierie & CAO ===
  AutoCAD: "Ingénierie & CAO",
  "Autodesk Inventor": "Ingénierie & CAO",
  SolidWorks: "Ingénierie & CAO",
  CATIA: "Ingénierie & CAO",
  "Siemens NX": "Ingénierie & CAO",
  "PTC Creo": "Ingénierie & CAO",
  "Fusion 360": "Ingénierie & CAO",
  SketchUp: "Ingénierie & CAO",
  ArchiCAD: "Ingénierie & CAO",
  Revit: "Ingénierie & CAO",
  "Civil 3D": "Ingénierie & CAO",
  MicroStation: "Ingénierie & CAO",
  "Rhino 3D": "Ingénierie & CAO",
  ANSYS: "Ingénierie & CAO",
  "COMSOL Multiphysics": "Ingénierie & CAO",
  Simulink: "Ingénierie & CAO",
  LabVIEW: "Ingénierie & CAO",
  "PLC Programming": "Ingénierie & CAO",
  "Siemens TIA Portal": "Ingénierie & CAO",
  "Schneider EcoStruxure": "Ingénierie & CAO",
  "Solid Edge": "Ingénierie & CAO",
  "GD&T (Tolérancement géométrique)": "Ingénierie & CAO",

  // === Architecture & Construction ===
  BIM: "Architecture & Construction",
  "REVIT MEP": "Architecture & Construction",
  "REVIT Structure": "Architecture & Construction",
  Navisworks: "Architecture & Construction",
  "Tekla Structures": "Architecture & Construction",
  "Études de structure": "Architecture & Construction",
  "Calcul béton armé": "Architecture & Construction",
  "Calcul charpente métallique": "Architecture & Construction",
  "Réalisation de plans d'exécution": "Architecture & Construction",
  "Règlementation thermique (RT / RE2020)": "Architecture & Construction",
  Urbanisme: "Architecture & Construction",
  Topographie: "Architecture & Construction",
  "Autocad Architecture": "Architecture & Construction",

  // === Transport & Logistique ===
  "Gestion de stock": "Transport & Logistique",
  "Supply Chain Management": "Transport & Logistique",
  Logistique: "Transport & Logistique",
  "Gestion d'entrepôt": "Transport & Logistique",
  WMS: "Transport & Logistique",
  "Planification de tournées": "Transport & Logistique",
  Incoterms: "Transport & Logistique",
  "Import / Export": "Transport & Logistique",
  Douanes: "Transport & Logistique",

  // === Certifications & Permis ===
  "Permis B": "Certifications & Permis",
  "Permis A": "Certifications & Permis",
  "Permis AM": "Certifications & Permis",
  "Permis C": "Certifications & Permis",
  "Permis CE": "Certifications & Permis",
  "Permis D": "Certifications & Permis",
  "Permis BE": "Certifications & Permis",
  "CACES R489 (chariots élévateurs)": "Certifications & Permis",
  "CACES R482 (engins de chantier)": "Certifications & Permis",
  "CACES R486 (nacelles)": "Certifications & Permis",
  "Habilitation électrique (H0B0)": "Certifications & Permis",
  "Habilitation électrique (B1V)": "Certifications & Permis",
  "Habilitation travail en hauteur": "Certifications & Permis",
  "SST (Sauveteur Secouriste du Travail)": "Certifications & Permis",
  "PSC1 (Prévention et secours civiques)": "Certifications & Permis",
  "Premiers secours": "Certifications & Permis",
  "Carte BTP": "Certifications & Permis",
  "Carte professionnelle VTC": "Certifications & Permis",
  "FIMO / FCO": "Certifications & Permis",
  "Habilitation nucléaire (SCN / CSQ / RP)": "Certifications & Permis",

  // === Sciences & Recherche ===
  SPSS: "Sciences & Recherche",
  Stata: "Sciences & Recherche",
  SAS: "Sciences & Recherche",
  "R Studio": "Sciences & Recherche",
  "Analyse statistique": "Sciences & Recherche",
  "Plan d'expérience (DoE)": "Sciences & Recherche",
  "Rédaction scientifique": "Sciences & Recherche",
  "Revue de littérature": "Sciences & Recherche",
  "Gestion de références (Zotero, Mendeley)": "Sciences & Recherche",
  "Méthodologie de recherche": "Sciences & Recherche",
  "Contrôle qualité": "Sciences & Recherche",
  "Bonnes pratiques de laboratoire (BPL)": "Sciences & Recherche",
  "Bonnes pratiques de fabrication (BPF/GMP)": "Sciences & Recherche",

  // === Santé & Social ===
  "Dossier patient informatisé": "Santé & Social",
  "Prise de constantes": "Santé & Social",
  "Soins de base": "Santé & Social",
  "Éducation thérapeutique": "Santé & Social",
  "Relation d'aide": "Santé & Social",
  "Accompagnement social": "Santé & Social",
  "Gestion de conflit": "Santé & Social",
  "Animation de groupe": "Santé & Social",
  Psychoéducation: "Santé & Social",

  // === Hôtellerie & Restauration ===
  "Service en salle": "Hôtellerie & Restauration",
  "Service au bar": "Hôtellerie & Restauration",
  "Prise de commande": "Hôtellerie & Restauration",
  Encaissement: "Hôtellerie & Restauration",
  "Accueil client": "Hôtellerie & Restauration",
  Cuisine: "Hôtellerie & Restauration",
  "Préparation chaud / froid": "Hôtellerie & Restauration",
  "Hygiène HACCP": "Hôtellerie & Restauration",
  "Gestion de réservations": "Hôtellerie & Restauration",
  "Logiciel de caisse": "Hôtellerie & Restauration",
  Barista: "Hôtellerie & Restauration",
  "Room service": "Hôtellerie & Restauration",

  // === Autres compétences transverses / terrain ===
  "Relation client": "Soft Skills",
  "Accueil téléphonique": "Soft Skills",
  "Accueil physique": "Soft Skills",
  "Gestion de file d'attente": "Soft Skills",
  "Vente en magasin": "Business & Finance",
  Merchandising: "Business & Finance",
  "Encaissement (caisse)": "Business & Finance",
  "Prospection commerciale": "Business & Finance",
  "Cold calling": "Business & Finance",
  "Rédaction de comptes rendus": "Soft Skills",
  "Animation d'ateliers": "Soft Skills",
  "Formation d'utilisateurs": "Soft Skills",

  // === Autre ===
  "No-code": "Autre",
  "Low-code": "Autre",
  "Notion Templates": "Autre",
  "Automation (Zapier, Make)": "Autre",
};

export const SKILL_SUGGESTIONS = Object.keys(SKILLS_DATABASE);
